import type { DatabaseType, DatabaseCategory } from './connection';

export interface DbMetadata {
  label: string;
  category: DatabaseCategory;
  defaultPort: number | null;
  requiresHost: boolean;
  requiresFilePath: boolean;
  queryLanguage: string;
  badge: string;
  badgeClass: string;
  containerLabel: string;
  itemLabel: string;
  fieldLabel: string;
  group: string;
}

export const DB_METADATA: Record<DatabaseType, DbMetadata> = {
  PostgreSQL: {
    label: 'PostgreSQL',
    category: 'Relational',
    defaultPort: 5432,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'PG',
    badgeClass: 'badge-pg',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  MySQL: {
    label: 'MySQL',
    category: 'Relational',
    defaultPort: 3306,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'MY',
    badgeClass: 'badge-mysql',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  MariaDB: {
    label: 'MariaDB',
    category: 'Relational',
    defaultPort: 3306,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'MA',
    badgeClass: 'badge-mariadb',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  SQLite: {
    label: 'SQLite',
    category: 'Relational',
    defaultPort: null,
    requiresHost: false,
    requiresFilePath: true,
    queryLanguage: 'sql',
    badge: 'SL',
    badgeClass: 'badge-sqlite',
    containerLabel: 'Database',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  MSSQL: {
    label: 'SQL Server',
    category: 'Relational',
    defaultPort: 1433,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'MS',
    badgeClass: 'badge-mssql',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  Oracle: {
    label: 'Oracle',
    category: 'Relational',
    defaultPort: 1521,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'OR',
    badgeClass: 'badge-oracle',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  CockroachDB: {
    label: 'CockroachDB',
    category: 'Relational',
    defaultPort: 26257,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'CR',
    badgeClass: 'badge-cockroach',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'SQL',
  },
  Redshift: {
    label: 'Redshift',
    category: 'Analytics',
    defaultPort: 5439,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'RS',
    badgeClass: 'badge-redshift',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'Analytics',
  },
  ClickHouse: {
    label: 'ClickHouse',
    category: 'Analytics',
    defaultPort: 8123,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'CH',
    badgeClass: 'badge-clickhouse',
    containerLabel: 'Database',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'Analytics',
  },
  Snowflake: {
    label: 'Snowflake',
    category: 'Analytics',
    defaultPort: null,
    requiresHost: false,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'SF',
    badgeClass: 'badge-snowflake',
    containerLabel: 'Schema',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'Analytics',
  },
  BigQuery: {
    label: 'BigQuery',
    category: 'Analytics',
    defaultPort: null,
    requiresHost: false,
    requiresFilePath: false,
    queryLanguage: 'sql',
    badge: 'BQ',
    badgeClass: 'badge-bigquery',
    containerLabel: 'Dataset',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'Analytics',
  },
  MongoDB: {
    label: 'MongoDB',
    category: 'Document',
    defaultPort: 27017,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'json',
    badge: 'MO',
    badgeClass: 'badge-mongodb',
    containerLabel: 'Database',
    itemLabel: 'Collection',
    fieldLabel: 'Field',
    group: 'NoSQL',
  },
  Cassandra: {
    label: 'Cassandra',
    category: 'WideColumn',
    defaultPort: 9042,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'cql',
    badge: 'CA',
    badgeClass: 'badge-cassandra',
    containerLabel: 'Keyspace',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'NoSQL',
  },
  ScyllaDB: {
    label: 'ScyllaDB',
    category: 'WideColumn',
    defaultPort: 9042,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'cql',
    badge: 'SC',
    badgeClass: 'badge-scylladb',
    containerLabel: 'Keyspace',
    itemLabel: 'Table',
    fieldLabel: 'Column',
    group: 'NoSQL',
  },
  Redis: {
    label: 'Redis',
    category: 'KeyValue',
    defaultPort: 6379,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'redis',
    badge: 'RD',
    badgeClass: 'badge-redis',
    containerLabel: 'Database',
    itemLabel: 'Key',
    fieldLabel: 'Property',
    group: 'NoSQL',
  },
  Neo4j: {
    label: 'Neo4j',
    category: 'Graph',
    defaultPort: 7687,
    requiresHost: true,
    requiresFilePath: false,
    queryLanguage: 'cypher',
    badge: 'NJ',
    badgeClass: 'badge-neo4j',
    containerLabel: 'Database',
    itemLabel: 'Label',
    fieldLabel: 'Property',
    group: 'NoSQL',
  },
  DynamoDB: {
    label: 'DynamoDB',
    category: 'Document',
    defaultPort: null,
    requiresHost: false,
    requiresFilePath: false,
    queryLanguage: 'json',
    badge: 'DY',
    badgeClass: 'badge-dynamodb',
    containerLabel: 'Region',
    itemLabel: 'Table',
    fieldLabel: 'Attribute',
    group: 'Cloud',
  },
};

export const DB_GROUPS: { name: string; types: DatabaseType[] }[] = [
  {
    name: 'SQL',
    types: ['PostgreSQL', 'MySQL', 'MariaDB', 'SQLite', 'MSSQL', 'Oracle', 'CockroachDB'],
  },
  {
    name: 'Analytics',
    types: ['Redshift', 'ClickHouse', 'Snowflake', 'BigQuery'],
  },
  {
    name: 'NoSQL',
    types: ['MongoDB', 'Redis', 'Cassandra', 'ScyllaDB', 'Neo4j'],
  },
  {
    name: 'Cloud',
    types: ['DynamoDB'],
  },
];
